#!/usr/bin/env python2.7
import os
import sys

sys.path.insert(
    0,
    os.path.join(os.path.dirname(os.path.dirname(__file__)), "src")
)
import argparse
from PyQt5 import QtWidgets

import todo


def start_todo_todo():
    app = QtWidgets.QApplication(sys.argv)
    todo_window = todo.TodoWindow(
        desk_widget=todo.TodoDeskWidget(),
        dock_widget=todo.TodoDockWidget()
    )
    todo_window.show()
    app.exec_()


def get_version():
    return todo.version


parser = argparse.ArgumentParser(
    prog="todo", description="Personal Task Manager."
)
parser.add_argument(
    "-v", "--version",
    action="version",
    version="%(prog)s {}".format(get_version()),
    help="Display application version."
)
parser.set_defaults(func=start_todo_todo)
args = parser.parse_args()
args.func()
